# gives your workflow a name
# This name appears on any pull request or in the Actions tab
# The name is especially useful when there are multiple workflows in repository
name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
